DEBUG:MARKDOWN:Successfuly imported extension module "markdown.extensions.toc".
DEBUG:MARKDOWN:Successfully loaded extension "markdown.extensions.toc.TocExtension".
DEBUG:MARKDOWN:Successfuly imported extension module "markdown.extensions.toc".
DEBUG:MARKDOWN:Successfully loaded extension "markdown.extensions.toc.TocExtension".
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /computer/order_rud/
ERROR:django.request:Internal Server Error: /computer/order_rud/1/
Traceback (most recent call last):
  File "D:\Read_Learn\Python\LX\rest_learn\venv\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = get_response(request)
  File "D:\Read_Learn\Python\LX\rest_learn\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Read_Learn\Python\LX\rest_learn\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Read_Learn\Python\LX\rest_learn\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Read_Learn\Python\LX\rest_learn\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Read_Learn\Python\LX\rest_learn\venv\lib\site-packages\rest_framework\views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "D:\Read_Learn\Python\LX\rest_learn\venv\lib\site-packages\rest_framework\views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Read_Learn\Python\LX\rest_learn\venv\lib\site-packages\rest_framework\views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Read_Learn\Python\LX\rest_learn\venv\lib\site-packages\rest_framework\generics.py", line 284, in get
    return self.retrieve(request, *args, **kwargs)
  File "D:\Read_Learn\Python\LX\rest_learn\venv\lib\site-packages\rest_framework\mixins.py", line 56, in retrieve
    instance = self.get_object()
  File "D:\Read_Learn\Python\LX\rest_learn\eshop\eshop\eshop\computerapp\views.py", line 209, in get_object
    obj = Order.objects.get(user=user, id=self.kwargs['pk'])
  File "D:\Read_Learn\Python\LX\rest_learn\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Read_Learn\Python\LX\rest_learn\venv\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
computerapp.models.DoesNotExist: Order matching query does not exist.
DEBUG:MARKDOWN:Successfuly imported extension module "markdown.extensions.toc".
DEBUG:MARKDOWN:Successfully loaded extension "markdown.extensions.toc.TocExtension".
